version: '3'

services:
  # Test Container for Jenkins
  tests-ci:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - test-common.env
    volumes:
      - $PWD:/go/src/github.com/pennsieve/rehydration-service
    depends_on:
      - dynamodb-ci
      - minio-ci
    environment:
      - DYNAMODB_URL=http://dynamodb-ci:8000
      - MINIO_URL=http://minio-ci:9000
  dynamodb-ci:
    image: amazon/dynamodb-local
    restart: always
  minio-ci:
    image: minio/minio
    env_file:
      - test-common.env # contains root creds for minio
    command: server --console-address ":9001" /data
