version: '3'

services:
  # Test Container for Jenkins
  tests-ci:
    extends:
      file: docker-compose.test-common.yaml
      service: tests
    depends_on:
      - dynamodb-ci
    environment:
      - DYNAMODB_URL=http://dynamodb-ci:8000
  dynamodb-ci:
    extends:
      file: docker-compose.test-common.yaml
      service: dynamodb
