version: '3'

services:
  # Test Container for Jenkins
  tests-ci:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - test-common.env
    volumes:
      - $PWD:/go/src/github.com/pennsieve/rehydration-service
    depends_on:
      - dynamodb-ci
    environment:
      - DYNAMODB_URL=http://dynamodb-ci:8000
  dynamodb-ci:
    image: amazon/dynamodb-local
    restart: always
